### PR TITLE
Slim down compiled templates

### PR DESCRIPTION
**Pull request by smfoote**
Move a few more methods to the runtime, and remove whitespace in elements where whitespace is not significant

### CODE REVIEW

**Comment by smfoote** [comment]
@jimmyhchan @prashn64 Let me know what you think of this change. I am removing whitespace in elements where whitespace is not significant. The whitespace must include a newline, or it is left alone. The idea is mostly to reduce compiled template file size. Is this too aggressive?

**Comment by jimmyhchan** [comment]
seems reasonable but sounds like early optimization. thinking about my pull for multiple passes i see this happening as a whitespace removal pass -- that is you need to generate an html syntax tree that can be traversed by a whitespace stripper.  just an idea. not sure how reasonable.

**Comment by smfoote** [comment]
I'm going to wait until your compiler commit is done.

**Comment by smfoote** [comment]
Will send a new PR using a compiler transform pass.

**Pull request closed without merging**
